version: '3.1'
volumes:
  teamcity-server-datadir:
  teamcity-server-logs:
services:
 teamcity:
  image: jetbrains/teamcity-server:latest
  volumes:
  - teamcity-server-datadir:/data/teamcity_server/datadir
  - teamcity-server-logs:/opt/teamcity/logs
  ports:
   - 8111:8111
 teamcity-agent:
  image: marekkacprzak/teamcity-agent-with-compose:latest
  build: ./agent
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  environment:
   SERVER_URL: http://teamcity:8111